name = "xguesser"
pages_build_output_dir = "public"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "xguesser"
database_id = "de099d3f-6040-4ab2-93b4-15cf619eb6b7"

[vars]
GOOGLE_CLIENT_ID = "82272052763-bjr2jke27sv02bt9gst4d3jsjo8e32mn.apps.googleusercontent.com"

# GOOGLE_CLIENT_ID a SESSION_SECRET nastav jako secrets,
# ne tady v souboru:
#   npx wrangler pages secret put SESSION_SECRET
#   npx wrangler pages secret put GOOGLE_CLIENT_ID
